"""Initial schema — autogenerated baseline for all PayFlow tables."""
revision = "0001_initial"
down_revision = None

from alembic import op  # noqa: F401
# NOTE: Production deployments should run `alembic revision --autogenerate` from
# models. The app also creates tables on startup for dev convenience.
# This migration marks the baseline; schema is defined in app/models.


def upgrade():
    pass


def downgrade():
    pass
